## Questão 3)

Um inseto se move aleatoriamente em um tabuleiro de tamanho 5 × 5 de acordo com a seguinte regra: a cada movimento ele tem igual probabilidade de saltar para alguma das casas adjacentes àquela ocupada, onde não considera-se casas na diagonal como adjacentes; porém, na casa do canto superior esquerdo há uma armadilha que imobiliza o inseto; na casa do canto inferior direito há um portal que transporta o inseto para qualquer outra casa do tabuleiro, com igual probabilidade; finalmente, nas casas dos cantos superior direito e inferior esquerdo há portais que transportam o inseto entre essas casas somente. Com base nessa descrição, faça o que se pede abaixo.

### A) Justifique que uma cadeia de Markov é um modelo adequado para descrever tal situação, e construa a matriz de probabilidades de transição de tal processo.

Uma cadeia de Markov é basicamente "Uma sequência finita X, $X_1$, $X_2$, ... de variáveis aleatórias, onde cada $X_i$ assume valores em um conjunto finito ou enumerável, e satisfaz a propriedade de Markov, ou seja, a probabilidade de $X_{n+1}$ assumir um valor depende apenas do valor atual $X_n$ e não dos valores anteriores $X_1$, $X_2$, ..., $X_{n-1}$". Nesse contexto, como a observação de $X_{n+1}$ depende apenas do valor atual $X_n$, podemos dizer que a cadeia de Markov é um modelo adequado para descrever a situação, pois:

Pode-se representar o movimento do inseto no tabuleiro em 25 estados, onde cada estado representa uma casa do tabuleiro. A cada movimento, o inseto tem igual probabilidade de saltar para alguma das casas adjacentes àquela ocupada, onde não se considera casas na diagonal como adjacentes. Portanto, a probabilidade de saltar para uma casa adjacente é de 1/4, exceto nas casas posicionadas na borda do tabuleiro, onde a probabilidade de saltar para uma casa adjacente é de 1/3. Além disso, nas casas dos cantos superior direito e inferior esquerdo há portais que transportam o inseto entre essas casas somente, ficando em um loop infinito entre essas casas. Por fim, no canto superior esquerdo há uma armadilha que imobiliza o inseto, e no canto inferior direito há um portal que transporta o inseto para qualquer outra casa do tabuleiro, com igual probabilidade.

Neste contexto, podemos perceber que o processo de analisar a probabilidade de cada movimento no tabuleiro depende apenas da ultima casa que o inseto estava, ou seja, a probabilidade de saltar para uma casa adjacente depende apenas da casa atual, e não das casas anteriores. Portanto, podemos dizer que a cadeia de Markov é um modelo adequado para descrever a situação.

Montando a matriz de probabilidades de transição, utilizando a notação $P_{ij}$ para representar a probabilidade de saltar da casa $i$ para a casa $j$, em que cada casa é representada por um número de 1 a 25 (da esquerda para a direita, de cima para baixo), temos:


In [82]:
import numpy as np

Este será o tabuleiro utilizado para representar a matriz de probabilidades de transição:
\begin{bmatrix}
0 & 1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 & 9 \\
10 & 11 & 12 & 13 & 14 \\
15 & 16 & 17 & 18 & 19 \\
20 & 21 & 22 & 23 & 24 \\
\end{bmatrix}


O código abaixo foi utilizado para montar a matriz de probabilidades de transição:

In [83]:
def create_line_markov(lines, columns):
    
    markov = np.zeros((25))

    if lines == 0 and columns == 0: # Armadilha
        markov[0] = 1
        return markov
    
    elif lines == 0 and columns == 4: # Portal 1
        markov[20] = 1
        return markov
    
    elif lines == 4 and columns == 0: # Portal 2
        markov[4] = 1
        return markov
    
    elif lines == 4 and columns == 4: # Portal Randômico
        for i in range(0, 24):
            markov[i] = 1/24
        return markov
    
    # Linhas e colunas da borda
    elif lines == 0: 
        markov[columns-1] = 1/3
        markov[columns+1] = 1/3
        markov[columns+5] = 1/3
        return markov

    elif lines == 4:
        markov[lines*5+columns-1] = 1/3
        markov[lines*5+columns+1] = 1/3
        markov[lines*5+columns-5] = 1/3
        return markov
    
    elif columns == 0:
        markov[lines*5+1] = 1/3
        markov[lines*5-5] = 1/3
        markov[lines*5+5] = 1/3
        return markov
    
    elif columns == 4:
        markov[lines*5+columns-1] = 1/3
        markov[lines*5+columns+5] = 1/3
        markov[lines*5+columns-5] = 1/3
        return markov
    
    # Linhas e colunas do meio
    else: 
        markov[lines*5+columns-1] = 1/4
        markov[lines*5+columns+1] = 1/4
        markov[lines*5+columns-5] = 1/4
        markov[lines*5+columns+5] = 1/4
        return markov

def create_matrix_markov():
    matrix = np.zeros((25, 25))
    for i in range(0, 25):
        matrix[i] = create_line_markov(i//5, i%5)
    return matrix


In [109]:
P = create_matrix_markov()

# Teste de soma das linhas
for i in range(0, 25):
    assert(np.sum(P[i]) == 1)

# P[i] é a linha i da matriz de transição
np.set_printoptions(suppress=True, precision=5)
P[19].view()

array([0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.33333, 0.     , 0.     , 0.     , 0.33333, 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.33333])

In [110]:
P.view()

array([[1.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
        0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
        0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
        0.     , 0.     , 0.     , 0.     ],
       [0.33333, 0.     , 0.33333, 0.     , 0.     , 0.     , 0.33333,
        0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
        0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
        0.     , 0.     , 0.     , 0.     ],
       [0.     , 0.33333, 0.     , 0.33333, 0.     , 0.     , 0.     ,
        0.33333, 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
        0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
        0.     , 0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.33333, 0.     , 0.33333, 0.     , 0.     ,
        0.     , 0.33333, 0.     , 0.     , 0.     , 0.     , 0.     ,
        0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
        0.   

### B) Construa um algoritmo para simular a posição do inseto, onde é possível selecionar a casa do tabuleiro onde o inseto localiza-se inicialmente.

O código abaixo foi utilizado para simular a posição do inseto, usando a propriedade de Markov e o Método da Potência para encontrar a distribuição de probabilidade da posicao do inseto no tabuleiro após um número $n$ de movimentos. Para isso, basta elevar o vetor de distribuição de probabilidade inicial $v_0$ à matriz de probabilidades de transição $P$, $n$ vezes, ou seja, $v_n = v_0 * P^n$. Esse método será ideal para calcular a distribuição de probabilidade da posição do inseto em infinitos passos, já que a matriz converge para um vetor de distribuição de probabilidade estável, como veremos na próxima questão. Além disso, foi feito outro método para simular, de fato, a posição do inseto no tabuleiro, onde o inseto é movido de acordo com a distribuição de probabilidade encontrada a cada posição.

In [86]:
def simulacao_tabuleiro_prob(posicao_inicial, P, n):
    posicao = np.zeros((25))
    posicao[posicao_inicial] = 1

    Pn = np.linalg.matrix_power(P, n)

    return np.dot(posicao, Pn)

In [87]:
# Exemplo de simulação de probabilidade de estar em cada posição do tabuleiro após 10 jogadas, começando na posição 15
Prob =simulacao_tabuleiro_prob(15, P, 10)
print(sum(Prob))
np.set_printoptions(suppress=True)
Prob.view()

0.9999999999999999


array([0.1124547 , 0.01967696, 0.00104216, 0.0152043 , 0.53138163,
       0.02536069, 0.00126614, 0.0391354 , 0.00126614, 0.0133135 ,
       0.00104216, 0.05100437, 0.00140599, 0.03442021, 0.00104216,
       0.02707327, 0.00126614, 0.04532064, 0.00126614, 0.01496178,
       0.01585432, 0.02421393, 0.00104216, 0.01967696, 0.00030812])

In [88]:
# Exemplo de simulação de probabilidade de estar em cada posição do tabuleiro após 100000 jogadas, começando na posição 15
Prob =simulacao_tabuleiro_prob(15, P, 100000)
print(sum(Prob))
np.set_printoptions(suppress=True)
Prob.view()

0.9999999999999994


array([0.22836879, 0.        , 0.        , 0.        , 0.65177305,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.11985816, 0.        , 0.        , 0.        , 0.        ])

In [89]:
def simulacao_tabuleiro(posicao_inicial, P):
    posicao = np.random.choice(25, p=P[posicao_inicial]) # Escolhe um número de 0 a 24 com base na probabilidade de cada posição
    return posicao

In [90]:
# Somente por curiosidade, mas não é necessário para o projeto.
def simulacao_tabuleiro_rapido(posicao_inicial, P, n):
    posicao = posicao_inicial
    Pn = np.linalg.matrix_power(P, n)
    for _ in range(0, n):
        posicao = np.random.choice(25, p=Pn[posicao]) # Escolhe um número de 0 a 24 com base na probabilidade de cada posição
    return posicao

In [111]:
# Teste da simulacao_tabuleiro para saber se a distribuição de probabilidades é a esperada

total = []

for _ in range(0, 10000):
    casa = simulacao_tabuleiro(15, P)
    total.append(casa)

print(np.bincount(total)/10000)

[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.3374 0.     0.     0.     0.     0.     0.3282 0.     0.     0.
 0.3344]


In [125]:
# Exemplo de simulação
casa = 1
passos = 15

for _ in range(0, passos):
    casa = simulacao_tabuleiro(casa, P)
    print("Caiu na casa:", casa)
    
print("\nTerminou na casa", casa)

Caiu na casa: 6
Caiu na casa: 5
Caiu na casa: 6
Caiu na casa: 11
Caiu na casa: 16
Caiu na casa: 11
Caiu na casa: 10
Caiu na casa: 15
Caiu na casa: 10
Caiu na casa: 15
Caiu na casa: 20
Caiu na casa: 4
Caiu na casa: 20
Caiu na casa: 4
Caiu na casa: 20

Terminou na casa 20


### C) Utilizando o algoritmo do item b), encontre uma aproximação para a probabilidade do inseto ser capturado pela armadilha do tabuleiro. Note que tal quantidade será função da casa inicialmente ocupada pelo inseto. Justifique intuitivamente o resultado obtido.

Usando o método explicado anteriormente:

In [93]:
def prob_capturado(posicao_inicial, P, n):
    Prob = simulacao_tabuleiro_prob(posicao_inicial, P, n)
    return Prob[0] # Retorna a probabilidade de estar na casa 0

In [101]:
# Exemplo de probabilidade de ser capturado
#casa = 14
passo = 100000000 # Basicamente infinito, porém não importa, a probabilidade converge bem antes disso

for i in range(25):
    print("Probabilidade de ser capturado na casa", i, "em", passo, "passos:", prob_capturado(i, P, passo))

Probabilidade de ser capturado na casa 0 em 100000000 passos: 1.0
Probabilidade de ser capturado na casa 1 em 100000000 passos: 0.6439716312056735
Probabilidade de ser capturado na casa 2 em 100000000 passos: 0.41843971631205656
Probabilidade de ser capturado na casa 3 em 100000000 passos: 0.22836879432624108
Probabilidade de ser capturado na casa 4 em 100000000 passos: 0.0
Probabilidade de ser capturado na casa 5 em 100000000 passos: 0.6439716312056735
Probabilidade de ser capturado na casa 6 em 100000000 passos: 0.5134751773049642
Probabilidade de ser capturado na casa 7 em 100000000 passos: 0.38297872340425504
Probabilidade de ser capturado na casa 8 em 100000000 passos: 0.2666666666666663
Probabilidade de ser capturado na casa 9 em 100000000 passos: 0.17163120567375867
Probabilidade de ser capturado na casa 10 em 100000000 passos: 0.41843971631205656
Probabilidade de ser capturado na casa 11 em 100000000 passos: 0.3829787234042551
Probabilidade de ser capturado na casa 12 em 100000

### D) Também usando o algoritmo do item b), encontre uma aproximação para o número médio de saltos que o inseto dá antes de ser capturado pela armadilha. Analogamente ao item c), isso também será uma função da casa inicialmente ocupada no tabuleiro. Qual casa inicial maximiza o número médio de saltos do inseto antes de ser capturado?

Neste caso, ignoramos o caso em que o inseto entra no loop 4,20 -> 20,4, pois o inseto nunca será capturado pela armadilha. Portanto, o número médio de saltos que o inseto dá antes de ser capturado pela armadilha é:

In [95]:
def media_saltos_captura(posicao_inicial, P, n):
    lista_saltos = []
    for _ in range(0, n):
        posicao = posicao_inicial
        counter = 0
        
        while posicao != 0:
            posicao = simulacao_tabuleiro(posicao, P)
            if posicao == 4 or posicao == 20:
                break
            counter += 1

        #print(counter)
        if posicao == 0:
            lista_saltos.append(counter)

    return np.mean(lista_saltos)
        

In [129]:
# Exemplo de média de saltos até ser capturado
print("Média de saltos até ser capturado:", media_saltos_captura(1, P, 10000))

Média de saltos até ser capturado: 6.2661402693915464


In [130]:
maior = 0
for i in [0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24]:
    media = media_saltos_captura(i, P, 50000)
    print("Média de saltos até ser capturado na casa", i, ":", media)
    if media > maior:
        maior = media
        casa = i

print("\nA casa com maior média de saltos até ser capturado é a", casa, "com média de", maior, "saltos")


Média de saltos até ser capturado na casa 0 : 0.0
Média de saltos até ser capturado na casa 1 : 6.367968191842947
Média de saltos até ser capturado na casa 2 : 11.571127156789197
Média de saltos até ser capturado na casa 3 : 15.22342105263158
Média de saltos até ser capturado na casa 5 : 6.386483369182331
Média de saltos até ser capturado na casa 6 : 10.276596573208723
Média de saltos até ser capturado na casa 7 : 14.901156731971655
Média de saltos até ser capturado na casa 8 : 18.220272610889374
Média de saltos até ser capturado na casa 9 : 20.59213107188185
Média de saltos até ser capturado na casa 10 : 11.406270911002773
Média de saltos até ser capturado na casa 11 : 14.771534601714405
Média de saltos até ser capturado na casa 12 : 18.161582259514535
Média de saltos até ser capturado na casa 13 : 20.439284192586282
Média de saltos até ser capturado na casa 14 : 21.047998711443988
Média de saltos até ser capturado na casa 15 : 15.028178936245157
Média de saltos até ser capturado na c

In [131]:
maior = 0
for i in [0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24]:
    media = media_saltos_captura(i, P, 50000)
    print("Média de saltos até ser capturado na casa", i, ":", media)
    if media > maior:
        maior = media
        casa = i

print("\nA casa com maior média de saltos até ser capturado é a", casa, "com média de", maior, "saltos")

Média de saltos até ser capturado na casa 0 : 0.0
Média de saltos até ser capturado na casa 1 : 6.265873384772706
Média de saltos até ser capturado na casa 2 : 11.489088205669336
Média de saltos até ser capturado na casa 3 : 15.244812188074599
Média de saltos até ser capturado na casa 5 : 6.253668372886614
Média de saltos até ser capturado na casa 6 : 10.41053078884339
Média de saltos até ser capturado na casa 7 : 14.93307478643677
Média de saltos até ser capturado na casa 8 : 18.37636173705417
Média de saltos até ser capturado na casa 9 : 20.645538243626063
Média de saltos até ser capturado na casa 10 : 11.513588252121675
Média de saltos até ser capturado na casa 11 : 14.902870788558376
Média de saltos até ser capturado na casa 12 : 18.245128698580707
Média de saltos até ser capturado na casa 13 : 20.32679600731056
Média de saltos até ser capturado na casa 14 : 21.263392857142858
Média de saltos até ser capturado na casa 15 : 15.249801674746584
Média de saltos até ser capturado na cas

Por conta da aleatoriedade adicionada pela casa 24, o número médio de saltos que o inseto dá antes de ser capturado pela armadilha há uma margem de erro perceptível. Por análise, temos que a maior média de saltos é obtida quando o inseto começa na casa 22 mais frequentemente, porém as vezes a casa 14 e 18 são as que mais dão saltos antes de serem capturadas. Tal resultado faz bastante sentido, já que a casa com maior número médio de saltos deve ser uma casa distante da armadilha (exceto a casa 24, devido a sua randomicidade), e as casas 14, 18 e 22 são as mais distantes da armadilha.

### E) Assumindo que a posição inicial do inseto é a casa central, quantas outras visitas ele faz, em média, à casa central, antes de ser capturado pela armadilha?

In [98]:
def visita_casa_central(P, n):
    media = 0
    for _ in range(0, n):
        soma = 0
        posicao = 12 # Posição central
        while True:
            posicao_n = simulacao_tabuleiro(posicao, P)
            
            # Se cair em uma armadilha ou portal, zera a soma e começa de novo
            if posicao_n == 20 or posicao_n == 4:
                soma = 0
                n -= 1
                break

            elif posicao == 0:
                break

            elif posicao_n == 12:
                soma += 1
            
            else:
                posicao = posicao_n
        media += soma
    return media/n

In [132]:
print("\nMédia de visitas à casa central:", visita_casa_central(P, 100000))


Média de visitas à casa central: 1.3099557721816049
